name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        TAG=$(git rev-parse HEAD | head -c 5)
        docker build . --file project/techtrends/Dockerfile --tag techtrends:$TAG
      

    - uses: docker/login-action@v2
    - name: Login to dockerhub
      with:
        username: aerosouund
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: push image
      run: docker push aerosouund/techtrends:latest


      
    
      

  
